### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/BookStore#1]

**Comment by PALASH2201** [comment]
I saw your repo, and the demo video. I can contribute to this issue. Please assign this to me

**Comment by harshit1142** [comment]
@PALASH2201 Sure. Do star ⭐ the repo and follow me to start. 

Also, there is a project link : https://bookstore-ochre-psi.vercel.app/

**Comment by PALASH2201** [comment]
Any specific type of requirements you would like to discuss?

**Comment by harshit1142** [comment]
@PALASH2201 Feel free to change. I guess changing the card design and button design would look good.

**Comment by PALASH2201** [comment]
Yea, I'll get started

**Comment by PALASH2201** [comment]
https://github.com/user-attachments/assets/bcf4e5f5-8677-4e49-86e0-2982b2994030

Does this look good to you? @harshit1142

**Comment by harshit1142** [comment]
@PALASH2201 Look excellent, Great work !!. 
can you also modify the search box too?

Just make a PR. Add video /screenshots in your PR

**Comment by ripu2** [comment]
Hey @harshit1142 , First of all great job @PALASH2201 . But I feel UI can be more attractive

**Comment by PALASH2201** [comment]
@harshit1142 Yea, I'll change the search box and the favourite book list too and get back to you as soon as possible

**Comment by harshit1142** [comment]
@PALASH2201 Appreciated.

**Comment by harshit1142** [comment]
@ripu2 after @PALASH2201 contribution, I will assign you too.

**Comment by PALASH2201** [comment]
@harshit1142 I have implemented till this, what's your take? 

https://github.com/user-attachments/assets/d76f9e62-758d-4003-8f58-488f1400202e

What should be the  colour scheme for books in fav list?

**Comment by harshit1142** [comment]
@PALASH2201 Excellent work. It looks excellent. You can make a pull request.

**Comment by PALASH2201** [comment]
I have initiated a Pull Request, but Vercel has shown some error, I guess the free version of Vercel does not allow more than 100 deployments.  Also the git guardian is not allowing cause the api key is exposed. So .env is required

**Comment by harshit1142** [comment]
@PALASH2201 don't worry. It's merged.
