### ISSUE TITLE
Add your Favorite in BookStore [Open to ALL]

### ISSUE THREAD

**Issue by harshit1142** [harshit1142/BookStore#11]
Add a Book in src/bookStore.js 

Do Mention #11 in your pull request description.

**Comment by Kamp7** [comment]
@harshit1142 assign me this issue

**Comment by lakshitrajput** [comment]
Can you assign me this issue?

**Comment by harshit1142** [comment]
@lakshitrajput Sure. Do star ⭐ the repo and good to go.

**Comment by Arshad-ashuu** [comment]
i would like to add a book . can you assign me this @harshit1142

**Comment by harshit1142** [comment]
@Arshad-ashuu Make a PR.
