### ISSUE TITLE
Feature request: To add cover image of books on the home page

### ISSUE THREAD

**Issue by Prathamesh0901** [harshit1142/BookStore#24]
Google api does provide the image link of the book's cover. If we showcase that on the homepage alongside the books information it would be great for the users.
I have already worked on this kind of feature, just that I used different api.
Take a look: https://book-management-bay.vercel.app/books
![image](https://github.com/user-attachments/assets/ac33426d-2f92-4556-ae3f-ca221d4b30ee)

So, I would love to contribute in this project and would love to add this feature!

**Comment by harshit1142** [comment]
@Prathamesh0901 Sure, you can add this . But there is also a section for "Contributed Books" so add a static image URL as it is for good-first-issue. ( Modify bookstore.js)

Do add Screenshots in your PR.

Do star ⭐ the repo and follow me to start.

**Comment by harshit1142** [comment]
@Prathamesh0901 don't modify the current page. Instead, add a button for Google books and add a new page there showing books . Got ?

**Comment by Prathamesh0901** [comment]
No I don't get it. Please elaborate.

**Comment by harshit1142** [comment]
@Prathamesh0901 so, you are going to add a new API ,if I am not wrong.

**Comment by Prathamesh0901** [comment]
I actually thought you were fetching all the books from google api which are on the homepage. But now i noticed that these books have hardcode. No worries I will add the links to the cover image in bookstore.js which will use openlibray's api.

**Comment by harshit1142** [comment]
@Prathamesh0901 few are hardcode, rest are using googleapis. So, if it contains image URL add it .

**Comment by Prathamesh0901** [comment]
![image](https://github.com/user-attachments/assets/5457efed-9197-497c-b9bf-5e71a512a6dc)
is this ok? @harshit1142

**Comment by harshit1142** [comment]
@Prathamesh0901 make it look like a card.

**Comment by Prathamesh0901** [comment]
![image](https://github.com/user-attachments/assets/1079573b-ceb6-4c58-bf7e-e7ef96ae7337)
@harshit1142  ?

**Comment by harshit1142** [comment]
@Prathamesh0901 Make a PR
