### ISSUE TITLE
suggestion to redesign the ui

### ISSUE THREAD

**Issue by mohit2404** [harshit1142/BookStore#29]
its a bookstore so the ui should be minimal and we can add dark-mode in addition

**Comment by harshit1142** [comment]
@mohit2404 let you know soon.

**Comment by saikatsardar01** [comment]
We can add dark mode and it must be responsive, with colourful and animating background seen. assign this to me

**Comment by harshit1142** [comment]
@mohit2404 has been assigned.

**Comment by saikatsardar01** [comment]
Okay

**Comment by mohit2404** [comment]
> @mohit2404 has been assigned.

is it okay to use tailwindcss or I need to stick to vanila css
if I use tailwind css I will not override the previously written css

**Comment by harshit1142** [comment]
@mohit2404  stick to vanila css
