### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by aayu5hgit** [harshit1142/BookStore#32]
UI improvements to be done:
- Make a modern Navbar
- Book Cards UI should be enhanced
- Font spacing, sizing and styling to be improved

**Comment by harshit1142** [comment]
@aayu5hgit Someone is working on improving the functionality of the website. After that I will look to assign you.

**Comment by harshit1142** [comment]
@aayu5hgit you can work on it.

**Comment by aayu5hgit** [comment]
Great, thanks @harshit1142 .

**Comment by aayu5hgit** [comment]
Hey @harshit1142 , I've raised a PR for book cards UI ennhancement, kindly check

**Comment by harshit1142** [comment]
@aayu5hgit merged.
