### ISSUE TITLE
Optimize Search Functionality with Debouncing and UI Improvements

### ISSUE THREAD

**Issue by Chayandev** [harshit1142/BookStore#33]
**Description:**

The current search functionality in the web app is not dynamic. When a user types and presses the search button, the search request is sent, but it doesn't offer an optimized user experience. I would like to enhance both the UI of the search bar and improve its functionality using debouncing.

### Changes to Implement:

**1. UI Enhancements:**
 Add a search icon inside the search bar for better visual indication.
Include a "clear text" icon in the search bar that allows the user to quickly remove their search query with a single click.
Debouncing:

**2. Debouncing:** 
Implement debouncing with a delay of 500ms. This means that after the user stops typing, the search will only trigger after a 500ms delay. This will prevent unnecessary API calls and improve the performance of finding books.

**4. Clear Text Functionality:**

When the user clicks the "clear text" icon, the search input should be cleared instantly, and the previous search results should be reset.

**Expected Outcome:** The new search bar should provide a smoother, more responsive experience, improving the efficiency of the search process while enhancing the user interface.

@harshit1142  If you assign this issue to me, I will start work on it.

**Comment by harshit1142** [comment]
@Chayandev Sure.

**Comment by harshit1142** [comment]
Fixed
