### ISSUE TITLE
books image is not loading add new book to read

### ISSUE THREAD

**Issue by noobrehan18** [harshit1142/BookStore#45]
in Contributed Books menu image is not loading ig , its expired...Add new book Images link to contribute book section.. add new to book to db . Can you assign me and also add on Hacktoberfest? I can add more books in this
<img width="1418" alt="Screenshot 2024-10-14 at 12 03 42 PM" src="https://github.com/user-attachments/assets/721285f2-325c-4f57-863b-730343e7358d">

**Comment by harshit1142** [comment]
@REHAN-18 someone already assigned
