### ISSUE TITLE
Enhance UI

### ISSUE THREAD

**Issue by ghost** [harshit1142/BookStore#6]
I would like to enhance UI for this app.pls assign it to me.

**Comment by harshit1142** [comment]
@Visha17 can you suggest how you can enhance it ?

**Comment by ghost** [comment]
I can enhance background UI,color and icons..

**Comment by harshit1142** [comment]
@Visha17 Assigned. Do star ⭐ the repo and follow me to start.

**Comment by Kamp7** [comment]
Hi, I would like to make some change in add to favourite button

**Comment by harshit1142** [comment]
@Kamp7 make a new issue
